-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#ba005b', -- 背景
  base01 = '#ba005b', --较浅的背景色
  base02 = '#ffdad8',
  base03 = '#ba005b', -- 键盘字符，匹配大括号
  base04 = '#d9c0c5',
  base05 = '#ffb1c4', -- 括号，运算符
  base06 = '#3c2c30',
  base07 = '#453539',

  base08 = '#ffb59c',-- 变量名
  base09 = '#ffdad8', -- 整数、布尔值 (True/False)。
  base0A = '#f5b7b4', --类名 (Class)、搜索匹配到的背景
  base0B = '#ffb1c4', -- 字符串
  base0C = '#ffb59c',
  base0D = '#8f0044', -- 函数名
  base0E = '#f5b7b4', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#f6dce1', -- 选中文字背景
  fg = '#1d1013', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a18b8f', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ffb59c',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#f5b7b4',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#ba005b',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#f5b7b4', --底边
  fg = '#ffb1c4',
})
