-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#336b00', -- 背景
  base01 = '#336b00', --较浅的背景色
  base02 = '#c9ecc8',
  base03 = '#336b00', -- 键盘字符，匹配大括号
  base04 = '#c2c9b8',
  base05 = '#70e000', -- 括号，运算符
  base06 = '#2c3226',
  base07 = '#353b2f',

  base08 = '#96d4b4',-- 变量名
  base09 = '#c9ecc8', -- 整数、布尔值 (True/False)。
  base0A = '#adcfad', --类名 (Class)、搜索匹配到的背景
  base0B = '#70e000', -- 字符串
  base0C = '#96d4b4',
  base0D = '#255100', -- 函数名
  base0E = '#adcfad', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#dee5d3', -- 选中文字背景
  fg = '#0f150b', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8c9383', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#96d4b4',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#adcfad',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#336b00',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#adcfad', --底边
  fg = '#70e000',
})
