-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#6f5d00', -- 背景
  base01 = '#6f5d00', --较浅的背景色
  base02 = '#eae5ab',
  base03 = '#6f5d00', -- 键盘字符，匹配大括号
  base04 = '#cec6b0',
  base05 = '#e8c400', -- 括号，运算符
  base06 = '#353020',
  base07 = '#3e3929',

  base08 = '#c4cc84',-- 变量名
  base09 = '#eae5ab', -- 整数、布尔值 (True/False)。
  base0A = '#cec991', --类名 (Class)、搜索匹配到的背景
  base0B = '#e8c400', -- 字符串
  base0C = '#c4cc84',
  base0D = '#544600', -- 函数名
  base0E = '#cec991', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#ebe2cb', -- 选中文字背景
  fg = '#171306', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#97907c', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#c4cc84',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#cec991',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#6f5d00',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#cec991', --底边
  fg = '#e8c400',
})
